# Generated by Django 4.2.5 on 2023-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Continente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre del Pais')),
                ('Codigo', models.CharField(max_length=2, verbose_name='Codigo del Pais')),
                ('Poblacion', models.IntegerField(default=1, verbose_name='N° Poblacion del Pais')),
                ('Tipo', models.CharField(choices=[('1', 'Desarrollado'), ('2', 'SubDesarrollado')], max_length=1, verbose_name='Tipo de Pais')),
                ('Continente', models.ManyToManyField(to='Continente.continente')),
            ],
        ),
    ]
