# Generated by Django 4.2.5 on 2023-10-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['Nombre'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterField(
            model_name='pais',
            name='Codigo',
            field=models.CharField(max_length=3, verbose_name='Codigo del Pais'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='Tipo',
            field=models.CharField(choices=[('1', 'Desarrollado'), ('2', 'Sub-Desarrollado')], max_length=1, verbose_name='Tipo de Pais'),
        ),
    ]
