# Generated by Django 4.2.5 on 2023-10-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pais', '0002_alter_pais_options_alter_pais_codigo_alter_pais_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre de la Ciudad')),
                ('Codigo', models.CharField(max_length=3, verbose_name='Codigo de la Ciudad')),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pais.pais')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['Nombre'],
            },
        ),
    ]
