# Generated by Django 4.2.5 on 2023-10-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=60, verbose_name='Nombre del Pais')),
                ('Codigo', models.CharField(max_length=2, verbose_name='Codigo del Pais')),
                ('Descripcion', models.CharField(max_length=255, verbose_name='Descripcion del Idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['Nombre'],
            },
        ),
    ]
