# Generated by Django 4.2.5 on 2023-10-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pais', '0002_alter_pais_options_alter_pais_codigo_alter_pais_tipo'),
        ('Idioma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='Pais',
            field=models.ManyToManyField(to='Pais.pais'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='Codigo',
            field=models.CharField(max_length=2, verbose_name='Codigo de Idioma'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='Nombre',
            field=models.CharField(max_length=60, verbose_name='Idioma'),
        ),
    ]
