# Generated by Django 4.2.5 on 2023-10-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30, verbose_name='Nombre del Continente')),
                ('Extencion', models.CharField(max_length=20, verbose_name='Extension del Continente')),
            ],
        ),
    ]
